// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npxuorucygpzgiicxwpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5weHVvcnVjeWdwemdpaWN4d3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjMyMTAsImV4cCI6MjA2NTgzOTIxMH0.XBOuNaBk9HMKHzSxSc1Vz98sNvK8iY9kZ4n6dkfJLdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);